Adding a null check to creating new instances of objects
## Given

```
JavaBeanTester.builder(Test.class).checkEquals().test();
```

## Before
```
Cannot invoke "Object.hashCode()" because "x" is null
java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "x" is null
```

## After
```
Create new instance of class 'org.junit.jupiter.api.Test' resulted in null ==> expected: not <null>
```